#!/usr/bin/bash


currentWall=$(ls $HOME/.config/wallpapers/backgrounds/ | wofi --show dmenu)

rm $HOME/.config/wallpapers/current/$(ls $HOME/.config/wallpapers/current/)
cp $HOME/.config/wallpapers/backgrounds/$currentWall $HOME/.config/wallpapers/current/

rm $HOME/.config/hypr/hyprpaper.conf
touch $HOME/.config/hypr/hyprpaper.conf
echo "preload = /home/kirachan/.config/wallpapers/current/$(ls $HOME/.config/wallpapers/current/)" >> $HOME/.config/hypr/hyprpaper.conf
echo "wallpaper = eDP-1,/home/kirachan/.config/wallpapers/current/$(ls $HOME/.config/wallpapers/current/)" >> $HOME/.config/hypr/hyprpaper.conf
echo "ipc = off" >> $HOME/.config/hypr/hyprpaper.conf

killall hyprpaper && hyprpaper
